### ISSUE TITLE
Unable to update or verify when no Open Fortress folder exists

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#40] opened 2023-03-05 02:45 UTC
### Summary
When the user does not have Open Fortress installed and they're opening OFToast, the update and verify buttons are disabled, preventing any attempt in installing the game through the launcher. This seems to happen irregardless of if Steam is installed (flatpak or native) or not.

This can be fixed by re-opening OFToast, as it'll create a `sourcemods/open_fortress/` folder where it's expected.

![image](https://user-images.githubusercontent.com/18003771/222938877-dc4f4905-947d-4a0f-ae89-3223af7b8e39.png)

### Step to reproduce
1. Do not have an `open_fortress/` folder where Toast expects it to be (usually `sourcemods/open_fortress/`).
2. Launch OFToast.
3. Observe that the update and verify buttons are uninteractable.

### What I expected
I should be able to initiate the installation procedure using the update button.

### What actually happened
It is impossible to verify or update on first boot.

### System Specifications
- **OFToast Version:** v0.0.0-[gitcommit](https://github.com/Superdiffusion/oftoast2/commit/dd77c3a67cd41a9a7d772d898aa99a8e1167af34)
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.14-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.6
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment] 2023-03-05 03:36
This is actually as designed - if it can't find where to install OF (ie no steam) it needs the user to manually enter it.
The issue is that's not working correctly here. I'll take a look.

**Comment by int-72h** [comment] 2023-03-12 19:42
Can't reproduce this with no OF installed.

**Comment by int-72h** [comment] 2023-03-13 22:51
Closing, if you're able to reproduce this consistently on the latest commit, then please reopen.

**Closed as completed by int-72h** 2023-03-13 22:51 UTC
Labels: bug, Medium, can't reproduce, Misc
